// The label table for the loader page, in both languages.
//
// The editor's src/core/boot_data.ts held one table for two pages, and the
// split adr/0012 decided took that file to vorlaut-editor. What comes here is
// the loader's own keys and only those: load.*, cable.* and the err.cable_*
// sentences a Trouble carries a word for. docs/split-crossings.md's direction
// two named exactly this - t() and LANG copied, "the load.*, cable.* and
// err.cable_* keys move with it".
//
// Two copies of a label table are not two implementations of a format, so
// nothing here asks for a fixture set the way device/fixtures/ does. What they
// are is two files that can drift, and the drift that matters is a key that
// exists in one language and not the other: tests/run.py's test_language.py is
// what notices, and it reads this file the same way it read the last one.
//
// Grouped the way the source was grouped rather than sorted - by feature, in
// the order the page uses them. New keys go beside their neighbours.

/** The languages this page offers. The editor offers the same two, and the
 *  choice is shared through localStorage - see boot.ts. */
export const LANGUAGES = ["de", "en"];

/** English, for a browser that has never said otherwise. */
export const DEFAULT_LANGUAGE = "en";

export const TEXTS: Record<string, Record<string, string>> = {
  "de": {
    "cable.failed": "Übertragen fehlgeschlagen: {error}",
    "cable.failed_short": "fehlgeschlagen",
    "cable.looking": "Sucht das Gerät ...",
    "err.cable_no_device": "Es hat nichts geantwortet. Steckt das Kabel, und ist das Gerät wach? Aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel. Beim nächsten Druck wird wieder nach dem Anschluss gefragt.",
    "err.cable_device_older": "Das Gerät hat geantwortet, spricht aber eine ältere Fassung des Kabels (Version {device}, hier ist es {browser}). Es ist nicht kaputt - es braucht neuere Firmware. Auf dem Gerät hat sich nichts geändert, es liest weiter den Stand von vorher.",
    "err.cable_device_newer": "Das Gerät hat geantwortet, spricht aber eine neuere Fassung des Kabels (Version {device}, hier ist es {browser}). Dann ist diese Seite die ältere Hälfte: neu laden und noch einmal versuchen. Auf dem Gerät hat sich nichts geändert.",
    "cable.no_serial": "Dieser Browser kann nicht mit dem Kabel sprechen - Chrome und Edge können es. Geprüft und umgerechnet ist alles; in einen Ordner schreiben geht auch hier.",
    "cable.nothing": "Das Gerät hat diesen Stand schon.",
    "cable.plan": "{put} Datei(en) zu senden ({size} KiB), {remove} zu löschen, {keep} sind schon drauf.",
    "cable.removing": "löscht {done}/{total}: {name}",
    "cable.sending": "sendet {done}/{total}: {name}",
    "cable.sent": "Übertragen: {stored} Datei(en) gespeichert, {removed} entfernt, {size} KiB durchs Kabel.",
    "cable.sent_short": "übertragen",
    "cable.stopped": "Abgebrochen. Auf dem Gerät hat sich nichts geändert - es liest weiter den Stand von vorher.",
    "cable.stopped_short": "abgebrochen",
    "cable.stopped_tight": "Abgebrochen, nachdem schon Platz geschafft war: bis eine Übertragung einmal durchläuft, hat das Gerät stumme Tasten.",
    "cable.tight": "Für das Alte und das Neue zusammen ist kein Platz - deshalb wird zuerst gelöscht. Ein Abbruch lässt das Gerät dann unvollständig zurück.",
    "cable.timings": "Längste Pause {gap} ms, längster Schreibvorgang {stall} ms. Das Gerät gibt nach 4000 ms auf.",
    "err.cable_too_big": "Der Stand passt nicht auf das Gerät: {size} KiB gebaut, {free} KiB frei. Weniger Seiten oder kürzere Sätze.",
    "load.again": "Andere Datei wählen",
    "load.bad_sleep": "Die Schlafzeit in dieser Datei ist keine Sekundenzahl, die das Gerät lesen kann: {value}.",
    "load.compile_failed": "Umrechnen fehlgeschlagen: {error}",
    "load.compiled": "{files} Datei(en), {size} KiB für das Gerät.",
    "load.compiling": "Rechnet die Bilder und die Tabelle ...",
    "load.connect": "Anschluss wählen ...",
    "load.connect_lead": "Kabel einstecken und eine Taste am Gerät drücken, damit es wach ist - aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel. Dann hier den Anschluss wählen; der Browser fragt danach.",
    "load.file_is": "{name}, {size} KiB",
    "load.folder": "Stattdessen in einen Ordner schreiben",
    "load.folder_failed": "In den Ordner schreiben fehlgeschlagen: {error}",
    "load.folder_lead": "Dieselben Dateien auf die Festplatte, für mklittlefs oder die Werkbank - der Weg, der ohne Kabelprotokoll auskommt.",
    "load.folder_written": "{written} Datei(en) in {folder} geschrieben, {removed} entfernt, {size} KiB.",
    "load.here": "Die Datei bleibt auf diesem Rechner. Sie wird hier gelesen und hier umgerechnet, und hinaus geht allein das, was durch das Kabel in den Talker läuft.",
    "load.holds": "{sets} Seite(n), {filled} von {keys} Tasten belegt, {pictures} Bild(er), {sounds} Aufnahme(n).",
    "load.holds_language": "Das Gerät beschriftet sich selbst auf: {code}",
    "load.holds_no_voice": "Keine Stimme in der Datei - jede Taste bleibt stumm.",
    "load.holds_voice": "Gesprochen von: {voice}",
    "load.lead": "Diese Seite nimmt eine Datei, die der Editor für das Gerät ausgegeben hat, prüft sie, rechnet sie in das um, was der Talker liest, und schickt sie durchs Kabel.",
    "load.long_clip": "{label} Taste {slot}: „{text}“ dauert {seconds} s. So lange antwortet die Taste auf keinen Druck - das Gerät spielt ein Wort zu Ende, bevor es wieder hört.",
    "load.name_cut": "{label}: der Name ist {bytes} Bytes lang und wird auf dem Gerät nach {max} abgeschnitten.",
    "load.no_picture": "{label} Taste {slot}: zu {symbol} liegt kein Bild in der Datei - die Taste zeigt ein graues Kreuz.",
    "load.not_a_package": "{name} ist keine Datei für den Talker: {why}.",
    "load.nothing_wrong": "Nichts spricht dagegen.",
    "load.pick": "Datei wählen ...",
    "load.pick_hint": "Die .obz, die der Editor unter „Sammlung exportieren“ schreibt, mit „Für den Talker“ als Antwort - im ⋯ neben dem Namen der Sammlung.",
    "load.port": "Anschluss USB {vendor}:{product}",
    "load.port_plain": "Ein Anschluss, den der Browser nicht benennt",
    "load.ports": "{n} Anschlüsse freigegeben - welcher der Talker ist, zeigt sich beim Übertragen.",
    "load.preview": "So sieht es auf dem Gerät aus",
    "load.preview_empty": "nichts darauf",
    "load.preview_key": "Taste {n}: {what}",
    "load.preview_lead": "Jede Kachel ist so groß, wie eine Taste am Gerät wirklich ist: 15,21 mm. Und es sind genau die Bilder, die gleich durchs Kabel gehen - keine Vorhersage davon.",
    "load.preview_setkey": "Seitentaste",
    "load.reading": "Liest {name} ...",
    "load.refused": "So kann diese Datei nicht auf das Gerät.",
    "load.send": "Übertragen",
    "load.send_lead": "Alles, was das Gerät noch nicht hat, geht hinüber; was es schon hat, bleibt liegen.",
    "load.set": "Seite {n}",
    "load.set_named": "Seite {n} ({name})",
    "load.sleep_clamped": "Die Schlafzeit steht auf {value} Sekunden, und das Gerät nimmt nur {min} bis {max}. Es schläft nach {used} Sekunden ein.",
    "load.silent_key": "{label} Taste {slot}: zu „{text}“ liegt keine Aufnahme in der Datei - die Taste bleibt stumm.",
    "load.step_check": "2. Prüfen",
    "load.step_compile": "3. Umrechnen",
    "load.step_connect": "4. Verbinden",
    "load.step_file": "1. Datei wählen",
    "load.step_send": "5. Übertragen",
    "load.stop": "Abbrechen",
    "load.title": "Auf den Talker übertragen",
    "load.too_many_keys": "{label}: {keys} Tasten, und das Gerät hat {max} je Seite. Die darüber hinaus kommen nicht an.",
    "load.too_many_sets": "{sets} Seiten, und das Gerät hat Platz für {max}. Es würde diese Datei zurückweisen und danach nichts anzeigen. Im Editor Seiten entfernen und neu ausgeben.",
    "load.unknown_language": "Die Sprache {code} kennt das Gerät nicht - seine eigenen Hinweise blieben englisch.",
    "load.wont_decode": "Das Bild zu {symbol} lässt sich hier nicht lesen - die Taste zeigt ein graues Kreuz.",
  },
  "en": {
    "cable.failed": "Sending failed: {error}",
    "cable.failed_short": "failed",
    "cable.looking": "Looking for the device ...",
    "err.cable_no_device": "Nothing answered. Is the cable in, and is the device awake? Only a key press brings it out of sleep, not the cable. The next press will ask for the port again.",
    "err.cable_device_older": "The device answered, but it speaks an older version of the cable (version {device}, this page speaks {browser}). It is not broken - it needs newer firmware. Nothing on the device has changed; it still reads the state it had.",
    "err.cable_device_newer": "The device answered, but it speaks a newer version of the cable (version {device}, this page speaks {browser}). That makes this page the older half: reload it and try again. Nothing on the device has changed.",
    "cable.no_serial": "This browser cannot talk to the cable - Chrome and Edge can. Everything is checked and compiled, and writing into a folder still works here.",
    "cable.nothing": "The device already has this state.",
    "cable.plan": "{put} file(s) to send ({size} KiB), {remove} to remove, {keep} already there.",
    "cable.removing": "removing {done}/{total}: {name}",
    "cable.sending": "sending {done}/{total}: {name}",
    "cable.sent": "Sent: {stored} file(s) stored, {removed} removed, {size} KiB through the cable.",
    "cable.sent_short": "sent",
    "cable.stopped": "Stopped. Nothing on the device has changed - it still reads the state it had.",
    "cable.stopped_short": "stopped",
    "cable.stopped_tight": "Stopped after room had already been made: until a transfer runs through once, the device has silent keys.",
    "cable.tight": "There is no room for the old content and the new at once - so the clearing goes first. Stopping now leaves the device incomplete.",
    "cable.timings": "Longest gap {gap} ms, longest write {stall} ms. The device gives up after 4000 ms.",
    "err.cable_too_big": "This state does not fit on the device: {size} KiB built, {free} KiB free. Fewer pages, or shorter sentences.",
    "load.again": "Choose another file",
    "load.bad_sleep": "The sleep timeout in this file is not a number of seconds the device can read: {value}.",
    "load.compile_failed": "Compiling failed: {error}",
    "load.compiled": "{files} file(s), {size} KiB for the device.",
    "load.compiling": "Rendering the pictures and the table ...",
    "load.connect": "Choose the port ...",
    "load.connect_lead": "Plug the cable in and press a key on the device so that it is awake - only a key press brings it out of sleep, not the cable. Then choose the port here; the browser will ask.",
    "load.file_is": "{name}, {size} KiB",
    "load.folder": "Write into a folder instead",
    "load.folder_failed": "Writing into the folder failed: {error}",
    "load.folder_lead": "The same files onto the disk, for mklittlefs or the bench - the way in that needs no cable protocol at all.",
    "load.folder_written": "{written} file(s) written into {folder}, {removed} removed, {size} KiB.",
    "load.here": "The file stays on this computer. It is read here and compiled here, and the only thing that leaves is what runs down the cable into the talker.",
    "load.holds": "{sets} page(s), {filled} of {keys} keys with something on them, {pictures} picture(s), {sounds} recording(s).",
    "load.holds_language": "The device labels itself in: {code}",
    "load.holds_no_voice": "No voice in this file - every key stays silent.",
    "load.holds_voice": "Spoken by: {voice}",
    "load.lead": "This page takes a file the editor wrote for the device, checks it, turns it into what the talker reads, and sends it down the cable.",
    "load.long_clip": "{label} key {slot}: “{text}” runs for {seconds} s. For that whole time the key answers no press - the device finishes a word before it listens again.",
    "load.name_cut": "{label}: the name is {bytes} bytes long and the device cuts it after {max}.",
    "load.no_picture": "{label} key {slot}: there is no picture for {symbol} in this file - the key shows a grey cross.",
    "load.not_a_package": "{name} is not a file for the talker: {why}.",
    "load.nothing_wrong": "Nothing here stands in the way.",
    "load.pick": "Choose a file ...",
    "load.pick_hint": "The .obz the editor writes under “Export this collection”, answering “For the talker” - in the ⋯ beside the collection's name.",
    "load.port": "Port USB {vendor}:{product}",
    "load.port_plain": "A port the browser does not name",
    "load.ports": "{n} ports granted - which of them is the talker shows when it is sent.",
    "load.preview": "What the device will show",
    "load.preview_empty": "nothing on it",
    "load.preview_key": "Key {n}: {what}",
    "load.preview_lead": "Every tile is the size a key on the device really is: 15.21 mm. And these are the pictures that are about to go down the cable, not a prediction of them.",
    "load.preview_setkey": "Page key",
    "load.reading": "Reading {name} ...",
    "load.refused": "This file cannot go onto the device as it is.",
    "load.send": "Send",
    "load.send_lead": "Everything the device does not have yet goes across; what it already has stays where it is.",
    "load.set": "Page {n}",
    "load.set_named": "Page {n} ({name})",
    "load.sleep_clamped": "The sleep timeout says {value} seconds, and the device takes only {min} to {max}. It will fall asleep after {used}.",
    "load.silent_key": "{label} key {slot}: there is no recording for “{text}” in this file - the key stays silent.",
    "load.step_check": "2. Check",
    "load.step_compile": "3. Compile",
    "load.step_connect": "4. Connect",
    "load.step_file": "1. Choose the file",
    "load.step_send": "5. Send",
    "load.stop": "Stop",
    "load.title": "Onto the talker",
    "load.too_many_keys": "{label}: {keys} keys, and the device has {max} to a page. The ones past that never arrive.",
    "load.too_many_sets": "{sets} pages, and the device has room for {max}. It would refuse this file and then show nothing at all. Remove pages in the editor and write it out again.",
    "load.unknown_language": "The device does not know the language {code} - its own prompts would stay English.",
    "load.wont_decode": "The picture for {symbol} cannot be read here - the key shows a grey cross.",
  },
};
