// The label table for the loader page, in both languages.
//
// The editor's src/core/boot_data.ts held one table for two pages, and the
// split adr/0012 decided took that file to vorlaut-editor. What comes here is
// the loader's own keys and only those: load.*, cable.* and the err.cable_*
// sentences a Trouble carries a word for. docs/split-crossings.md's direction
// two named exactly this - t() and LANG copied, "the load.*, cable.* and
// err.cable_* keys move with it".
//
// Two copies of a label table are not two implementations of a format, so
// nothing here asks for a fixture set the way device/fixtures/ does. What they
// are is two files that can drift, and the drift that matters is a key that
// exists in one language and not the other: tests/run.py's test_language.py is
// what notices, and it reads this file the same way it read the last one.
//
// Grouped the way the source was grouped rather than sorted - by feature, in
// the order the page uses them. New keys go beside their neighbours.
//
// Two things a line here can carry beyond a plain {blank}. `{sets|Seite|Seiten}`
// is a count's own word, chosen by Intl.PluralRules against the same number -
// loader/src/fill.ts is the whole of it, and it exists because "2 Seite(n)" was
// the one line on this page that sounded like a program. And `{action}` in
// load.folder_lead is where a control goes inside a sentence: main.ts splits
// the filled line there and puts the button between the halves, so the words
// and their order stay in this file rather than being assembled from two
// fragments in a module that cannot know how a language builds a sentence.

/** The languages this page offers. The editor offers the same two, and the
 *  choice is shared through localStorage - see boot.ts. */
export const LANGUAGES = ["de", "en"];

/** English, for a browser that has never said otherwise. */
export const DEFAULT_LANGUAGE = "en";

export const TEXTS: Record<string, Record<string, string>> = {
  "de": {
    "cable.failed": "Übertragen fehlgeschlagen: {error}",
    "cable.failed_reading": "Das Gerät ließ sich nicht lesen: {error}",
    "cable.failed_short": "fehlgeschlagen",
    "cable.looking": "Sucht das Gerät ...",
    "cable.firmware": "Das Gerät meldet Firmware {version}.",
    "cable.firmware_unnamed": "Das Gerät nennt seine Firmware nicht - es trägt also einen Stand von vor dieser Zeile. Übertragen geht trotzdem.",
    "door.browsers": "Mit dem Kabel sprechen können Chrome und Edge. In Firefox und Safari bleibt die zweite Zeile: eine Datei prüfen und die Seiten sehen geht überall.",
    "door.connect": "Talker verbinden",
    "door.failed": "Es hat nichts geantwortet. Ist das Gerät wach? Aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel.",
    "door.wake_lead": "Ein Tastendruck holt den Talker aus dem Schlaf. Das Kabel nicht - also einmal drücken, bevor es losgeht.",
    "door.wake_title": "Wecken, dann einstecken",
    "door.without": "Kein Talker zur Hand? Trotzdem eine Datei prüfen",
    "err.cable_no_device": "Es hat nichts geantwortet. Steckt das Kabel, und ist das Gerät wach? Aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel. Beim nächsten Druck wird wieder nach dem Anschluss gefragt.",
    "err.cable_device_older": "Das Gerät hat geantwortet, spricht aber eine ältere Fassung des Kabels (Version {device}, hier ist es {browser}). Es ist nicht kaputt - es braucht neuere Firmware. Auf dem Gerät hat sich nichts geändert, es liest weiter den Stand von vorher.",
    "err.cable_device_newer": "Das Gerät hat geantwortet, spricht aber eine neuere Fassung des Kabels (Version {device}, hier ist es {browser}). Dann ist diese Seite die ältere Hälfte: neu laden und noch einmal versuchen. Auf dem Gerät hat sich nichts geändert.",
    "cable.no_serial": "Chrome und Edge können mit dem Kabel sprechen, dieser Browser nicht - hier gibt es also nichts zu drücken.",
    "cable.cost": "Diese Sammlung braucht {total} KiB. Davon liegen {already} KiB schon auf dem Gerät, es gehen also {needed} KiB hinüber; danach sind {free} KiB frei.",
    "cable.cost_collections": "Danach hält das Gerät {on} von {room} Sammlungen.",
    "cable.cost_one": "Dieses Gerät hält genau eine Sammlung. Was jetzt drauf ist, wird ersetzt - ältere Firmware kann nicht mehrere nebeneinander halten.",
    "cable.nothing": "Das Gerät hat diesen Stand schon.",
    "cable.plan": "{put} {put|Datei|Dateien} zu senden ({size} KiB), {remove} zu löschen, {keep} {keep|ist|sind} schon drauf.",
    "cable.removing": "löscht {done}/{total}: {name}",
    "cable.same_name": "Auf dem Gerät liegt schon eine andere Sammlung, die „{name}“ heißt. Im Menü stehen dann zwei gleiche Einträge - kaputt geht davon nichts, beide bleiben liegen, aber am Gerät ist nicht zu sehen, welcher welcher ist. Wer das nicht will, benennt im Editor die Sammlung oder ihre erste Seite anders und exportiert noch einmal.",
    "cable.sending": "sendet {done}/{total}: {name}",
    "cable.sent": "Übertragen: {stored} {stored|Datei|Dateien} gespeichert, {removed} entfernt, {size} KiB durchs Kabel.",
    "cable.sent_short": "übertragen",
    "cable.smaller": "Die Aufnahmen gehen komprimiert hinüber - das Gerät sagt, dass es sie abspielt.",
    "cable.smaller_unheard": "Dieser Talker spielt keine komprimierten Aufnahmen ab, sie gehen also unverändert hinüber. Er trägt einen Stand von vor dieser Möglichkeit - das ändert erst eine neuere Firmware.",
    "cable.stopped": "Abgebrochen. Auf dem Gerät hat sich nichts geändert - es liest weiter den Stand von vorher.",
    "cable.stopped_short": "abgebrochen",
    "cable.stopped_tight": "Abgebrochen, nachdem schon Platz geschafft war: bis eine Übertragung einmal durchläuft, hat das Gerät stumme Tasten.",
    "cable.tight": "Für das Alte und das Neue zusammen ist kein Platz - deshalb wird zuerst gelöscht. Ein Abbruch lässt das Gerät dann unvollständig zurück.",
    "cable.timings": "Längste Pause {gap} ms, längster Schreibvorgang {stall} ms. Das Gerät gibt nach 4000 ms auf.",
    "err.cable_too_many": "Das Gerät hält Platz für {room} Sammlungen und hätte danach {on}. Erst eine entfernen - weiter unten auf dieser Seite.",
    "err.cable_unreadable_collection": "Auf dem Gerät liegt eine Sammlung, die diese Seite nicht lesen kann ({name}). Solange sie da ist, lässt sich nicht sagen, welche Kacheln noch gebraucht werden - deshalb wird nichts gelöscht.",
    "err.cable_too_big": "Der Stand passt nicht auf das Gerät: {size} KiB gebaut, {free} KiB frei. Weniger Seiten oder kürzere Sätze.",
    "err.device_bad": "Das Gerät hat das Wort verstanden und den Rest der Zeile nicht. Das ist eine beschädigt angekommene Zeile und kein Fehler in der Datei; gespeichert wurde nichts. Noch einmal versuchen.",
    "err.device_crc": "Eine Datei ist vollständig angekommen und stimmt nicht mit ihrer Prüfsumme überein - unterwegs hat sich etwas an ihr verändert. Sie wurde verworfen statt gespeichert. Noch einmal versuchen; passiert es zweimal bei derselben Datei, ist das Kabel der Verdächtige.",
    "err.device_lost": "Das Dateisystem des Geräts hat mitten in einer Datei aufgehört, Bytes anzunehmen - meistens heißt das, der Speicher ist voll. Die halb geschriebene Datei wurde weggeworfen. Weiter unten auf dieser Seite eine Sammlung entfernen und noch einmal senden.",
    "err.device_missing": "Auf dem Gerät gibt es keine Datei namens {name} - beim Lesen der Liste war sie noch da. Noch einmal fragen; was das Gerät hält, hat sich seitdem geändert.",
    "err.device_nospace": "Eine Datei ist größer als der Platz, der auf dem Gerät übrig ist. Sie wurde zurückgewiesen, bevor irgendetwas davon gesendet wurde. Weiter unten eine Sammlung entfernen, oder die Aufnahmen kleiner senden.",
    "err.device_session": "Das Gerät hatte das Gespräch schon beendet, als das hier ankam. Das tut es, wenn eine Übertragung abbricht, und danach weist es alles zurück, bis es neu begrüßt wird. Noch einmal drücken fängt ein neues an. Halb geschrieben wurde nichts.",
    "err.device_short": "Das Gerät hat auf den Rest einer Datei gewartet, und er kam nicht. Die halb geschriebene Datei wurde weggeworfen, es liegt also keine halbe auf dem Gerät. Noch einmal versuchen - und wenn es immer an derselben Stelle passiert, liegt es am Kabel oder am Anschluss und nicht an der Datei.",
    "err.device_verb": "Das Gerät kennt eines der Wörter nicht, die diese Seite benutzt hat. Seine Firmware ist also älter als diese Seite. Die Versionsprüfung fängt das sonst vorher ab; wenn das hier steht, liegen die beiden weiter auseinander, als beide voneinander wissen.",
    "err.device_write": "Das Gerät konnte die Datei nicht schreiben ({name}), und warum, lässt sich von hier aus nicht sagen - meistens ist es ein Dateisystem, das unlesbar geworden ist. Unter diesem Namen wurde nichts gespeichert.",
    "flash.carries": "Diese Seite trägt Firmware {release}.",
    "flash.check": "Gerät prüfen",
    "flash.update_to": "Auf {release} aktualisieren",
    "flash.write_to": "{release} schreiben",
    "flash.writes_device": "schreibt das Gerät",
    "flash.check_lead": "Das Gerät muss wach sein - aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel.",
    "flash.checking": "Fragt das Gerät ...",
    "flash.device_says": "Auf dem Gerät ist Firmware {version}.",
    "flash.device_unnamed": "Das Gerät antwortet, nennt seine Firmware aber nicht: ein Stand von vor dieser Zeile.",
    "flash.same": "Das ist genau der Stand, den diese Seite trägt. Es ist nichts zu tun.",
    "flash.older": "Diese Seite trägt {release} und kann das Programm neu schreiben.",
    "flash.newer": "Das Gerät ist neuer als das, was diese Seite trägt. Dann ist die Seite die ältere Hälfte, und hier ist nichts zu schreiben.",
    "flash.unorderable": "{device} und {release} lassen sich nicht vergleichen - ein selbst übersetzter Stand trägt keine Nummer. Schreiben geht trotzdem, die Entscheidung liegt bei dir.",
    "flash.nothing_answered": "Es hat nichts geantwortet. Entweder schläft das Gerät - dann weckt es ein Tastendruck - oder auf diesem Anschluss ist kein Talker, oder er hat noch gar keine Firmware.",
    "flash.whole_warning": "Geschrieben werden Bootloader, Partitionstabelle und Programm. Inhalt, der auf dem Gerät liegt, ist danach weg: es startet leer und wird über das Kabel wieder gefüllt.",
    "flash.program_warning": "Geschrieben wird nur das Programm. Der Inhalt auf dem Gerät bleibt, wo er ist - und die Partitionstabelle auch. Ein Gerät, das noch die alte trägt, behält seinen kleinen Dateibereich, bis einmal alles geschrieben wird.",
    "flash.unnamed_unorderable": "Mit {release} vergleichen lässt sich das nicht - dieser Stand nennt sich selbst nicht. Schreiben geht trotzdem, die Entscheidung liegt bei dir.",
    "flash.write_mode_here": "Diese Seite schaltet das Gerät gleich selbst in den Schreibmodus - an einem fertigen Talker sind BOOT und RESET im Gehäuse und nicht zu erreichen. Dabei meldet sich der Anschluss ab und als anderer wieder an, und danach fragt der Browser noch einmal: dann ist USB JTAG/serial debug unit der richtige.",
    "flash.switching": "Schaltet um ...",
    "flash.download_mode": "Es hat nichts geantwortet, also kann diese Seite es auch nicht selbst umschalten: das muss am Board passieren - BOOT halten, RESET drücken, BOOT loslassen. An einem fertigen Talker sitzen beide im Gehäuse; dann hilft nur, es zu öffnen oder das Board vorher umzuschalten.",
    "flash.choose_and_write": "Anschluss wählen und schreiben",
    "flash.fetching": "Holt die Firmware ...",
    "flash.fetched": "Firmware geholt und geprüft: {size} KiB.",
    "flash.writing": "schreibt {done} von {total} KiB",
    "flash.written": "Geschrieben. Das Gerät startet neu; wenn es dunkel bleibt, einmal RESET drücken. Danach sagt Gerät prüfen, was jetzt drauf ist.",
    "flash.written_short": "geschrieben",
    "flash.failed": "Schreiben fehlgeschlagen: {error}",
    "flash.failed_short": "fehlgeschlagen",
    "err.flash_no_chip": "Auf diesem Anschluss meldet sich kein Chip im Schreibmodus. Der Schreibmodus ist ein anderer Anschluss als der des laufenden Talkers: BOOT halten, RESET drücken, BOOT loslassen - und dann den Anschluss wählen, der neu dazugekommen ist.",
    "err.flash_write_failed": "Das Schreiben ist mittendrin abgebrochen. Auf dem Gerät liegt jetzt womöglich nur ein Teil des Programms; es kann wiederholt werden, und dazwischen passiert nichts Schlimmeres.",
    "err.firmware_not_fetched": "Die Firmware-Datei dieser Seite ließ sich nicht laden. Neu laden und noch einmal versuchen.",
    "err.firmware_wrong_size": "Die geladene Firmware-Datei hat nicht die Länge, die diese Seite erwartet - sie ist unterwegs abgeschnitten worden. Es wurde nichts geschrieben.",
    "err.firmware_wrong_sum": "Die geladene Firmware-Datei stimmt nicht mit ihrer Prüfsumme überein. Es wurde nichts geschrieben.",
    "err.firmware_no_digest": "Dieser Browser kann hier keine Prüfsumme rechnen - das gibt es nur auf Seiten, die nicht über https ausgeliefert werden. Ungeprüft wird nichts geschrieben.",
    "load.again": "Andere Datei wählen",
    "load.bad_sleep": "Die Schlafzeit in dieser Datei ist keine Sekundenzahl, die das Gerät lesen kann: {value}.",
    "load.collections_check": "Nachsehen",
    "load.collections_keep": "Doch nicht",
    "load.collections_lead": "Was auf dem Gerät liegt, Sammlung für Sammlung - und der Weg, eine wieder loszuwerden. Das Gerät muss wach sein.",
    "load.collections_none": "Auf dem Gerät liegt keine Sammlung. Am Gerät selbst steht dasselbe im Menü unter Sammlung.",
    "load.collections_older": "Diese Firmware hält genau eine Sammlung, unter einem festen Namen - wie sie heißt, steht nicht in der Datei. Neuere Firmware hält mehrere nebeneinander; weiter unten steht, was diese Seite trägt.",
    "load.collections_really": "Wirklich entfernen",
    "load.collections_remove": "Entfernen",
    "load.collections_removed": "„{name}“ ist weg: {files} {files|Datei|Dateien} entfernt, {size} KiB frei geworden.",
    "load.collections_removed_short": "entfernt",
    "load.collections_room": "{on} von {room} {room|Sammlung|Sammlungen} auf dem Gerät, {free} KiB frei.",
    "load.collections_title": "Die Sammlungen auf dem Gerät",
    "load.collections_unreadable": "{file} liest diese Seite nicht - eine Sammlung aus einer anderen Fassung des Formats. Sie bleibt liegen: welche Kacheln sie braucht, ist von hier aus nicht zu sagen.",
    "load.collections_warning": "„{name}“ wird vom Gerät entfernt, mit allen Kacheln und Aufnahmen, die keine andere Sammlung mehr braucht: {frees} KiB. Das lässt sich nicht rückgängig machen - die Sammlung kommt aus dem Editor zurück, wenn sie dort noch liegt.",
    "load.cost": "Was kostet das?",
    "load.compile_failed": "Umrechnen fehlgeschlagen: {error}",
    "load.compiled": "{files} {files|Datei|Dateien}, {size} KiB für das Gerät.",
    "load.compiling": "Rechnet die Bilder und die Tabelle ...",
    "load.connect": "Anschluss wählen ...",
    "load.connect_lead": "Kabel einstecken und eine Taste am Gerät drücken, damit es wach ist - aus dem Schlaf holt es nur ein Tastendruck, nicht das Kabel. Dann hier den Anschluss wählen; der Browser fragt danach.",
    "load.firmware_title": "Die Firmware auf dem Gerät",
    "load.folder": "in einen Ordner schreiben",
    "load.folder_failed": "In den Ordner schreiben fehlgeschlagen: {error}",
    "load.folder_lead": "Dieselben Dateien auf die Festplatte, für mklittlefs oder die Werkbank - {action}.",
    "load.folder_written": "{written} {written|Datei|Dateien} in {folder} geschrieben, {removed} entfernt, {size} KiB.",
    "load.here": "Die Datei bleibt auf diesem Rechner. Sie wird hier gelesen und hier umgerechnet, und hinaus geht allein das, was durch das Kabel in den Talker läuft.",
    "load.holds": "{sets} {sets|Seite|Seiten}, {filled} von {keys} Tasten belegt, {pictures} {pictures|Bild|Bilder}, {sounds} {sounds|Aufnahme|Aufnahmen}.",
    "load.holds_collection": "Im Menü des Geräts heißt diese Sammlung „{name}“.",
    "load.holds_language": "Das Gerät beschriftet sich selbst auf {name}.",
    "load.holds_no_voice": "Keine Stimme in der Datei - jede Taste bleibt stumm.",
    "load.holds_voice": "Gesprochen von {voice}.",
    "lang.de": "Deutsch",
    "lang.en": "Englisch",
    "load.lead": "Diese Seite nimmt eine Datei, die der Editor für das Gerät ausgegeben hat, prüft sie, rechnet sie in das um, was der Talker liest, und schickt sie durchs Kabel.",
    "load.long_clip": "{label} Taste {slot}: „{text}“ dauert {seconds} s. So lange antwortet die Taste auf keinen Druck - das Gerät spielt ein Wort zu Ende, bevor es wieder hört.",
    "load.name_cut": "{label}: der Name ist {bytes} Bytes lang und wird auf dem Gerät nach {max} abgeschnitten.",
    "load.no_picture": "{label} Taste {slot}: zu {symbol} liegt kein Bild in der Datei - die Taste zeigt ein graues Kreuz.",
    "load.not_a_package": "{name} ist keine Datei für den Talker: {why}.",
    "load.nothing_wrong": "Nichts spricht dagegen.",
    "load.chip_blocked": "nicht hier",
    "load.chip_notes": "{n} {n|Hinweis|Hinweise}",
    "load.chip_refuses": "{n} {n|Einwand|Einwände}",
    "load.chip_size": "{size} KiB",
    "load.drop": "Die .obz hierher ziehen",
    "load.gate": "Dieser Browser kann das Gerät nicht erreichen. Für das Kabel braucht es Chrome oder Edge. Eine Datei prüfen und ansehen geht hier trotzdem.",
    "load.gate_more": "Diese Seite in Chrome oder Edge öffnen, wenn der Talker bereitliegt.",
    "load.notes_stand": "Die Hinweise aus der Prüfung gelten weiter - hier ist nichts dazugekommen.",
    "load.pick": "Datei wählen ...",
    "load.pick_hint": "Die .obz, die der Editor unter „Sammlung exportieren“ schreibt, mit „Für den Talker“ als Antwort - im ⋯ neben dem Namen der Sammlung.",
    "load.port": "Anschluss USB {vendor}:{product}",
    "load.port_plain": "Ein Anschluss, den der Browser nicht benennt",
    "load.ports": "{n} Anschlüsse freigegeben - welcher der Talker ist, zeigt sich beim Übertragen.",
    "load.preview": "So sieht es auf dem Gerät aus",
    "load.preview_empty": "nichts darauf",
    "load.preview_key": "Taste {n}: {what}",
    "load.preview_lead": "Jede Kachel ist so groß, wie eine Taste am Gerät wirklich ist: 15,21 mm. Und es sind genau die Bilder, die gleich durchs Kabel gehen - keine Vorhersage davon.",
    "load.preview_setkey": "Seitentaste",
    "load.reading": "Liest {name} ...",
    "load.refused": "So kann diese Datei nicht auf das Gerät.",
    "load.send": "Übertragen",
    "load.send_lead": "Alles, was das Gerät noch nicht hat, geht hinüber; was es schon hat, bleibt liegen.",
    "load.set": "Seite {n}",
    "load.set_named": "Seite {n} ({name})",
    "load.sleep_clamped": "Die Schlafzeit steht auf {value} Sekunden, und das Gerät nimmt nur {min} bis {max}. Es schläft nach {used} Sekunden ein.",
    "load.silent_key": "{label} Taste {slot}: zu „{text}“ liegt keine Aufnahme in der Datei - die Taste bleibt stumm.",
    "load.silent_key_untexted": "{label} Taste {slot}: diese Taste hat keine Wörter und keine Aufnahme - sie bleibt stumm.",
    "load.smaller": "Aufnahmen kleiner senden",
    "load.smaller_lead": "Ein Viertel der Größe und ein Viertel der Wartezeit am Kabel, bei hörbar schlechterer Qualität. Richtig für ein Spiel, in dem die Aufnahmen Wörter zum Zuordnen sind; falsch für eine Sammlung, über die jemand verstanden wird.",
    "load.step_check": "Prüfen",
    "load.step_check_ahead": "Was in der Datei steht, und was davon der Talker nicht kann. Es wird nichts geändert.",
    "load.step_compile": "Umrechnen",
    "load.step_compile_ahead": "Bilder, Aufnahmen und Seiten werden in die paar Dateien umgerechnet, die der Talker liest.",
    "load.step_connect": "Verbinden",
    "load.step_connect_ahead": "An welchen Talker das geht. Einmal gefragt, danach merkt der Browser sich den Anschluss.",
    "load.step_file": "Datei wählen",
    "load.step_send": "Übertragen",
    "load.step_send_ahead": "Datei für Datei durchs Kabel, mit dem Stand daneben. Bis hierher hat sich am Gerät nichts geändert.",
    "load.stop": "Abbrechen",
    "load.title": "Auf den Talker übertragen",
    "load.too_many_keys": "{label}: {keys} Tasten, und das Gerät hat {max} je Seite. Die darüber hinaus kommen nicht an.",
    "load.too_many_sets": "{sets} Seiten, und das Gerät hat Platz für {max}. Es würde diese Datei zurückweisen und danach nichts anzeigen. Im Editor Seiten entfernen und neu ausgeben.",
    "load.unknown_language": "Die Sprache {code} kennt das Gerät nicht - seine eigenen Hinweise blieben englisch.",
    "load.wont_decode": "Das Bild zu {symbol} lässt sich hier nicht lesen - die Taste zeigt ein graues Kreuz.",
    "talker.back": "Dein Talker",
    "talker.fact_collections": "Sammlungen",
    "talker.fact_firmware": "Firmware",
    "talker.fact_room": "Platz frei",
    "talker.holding": "Was darauf liegt",
    "talker.of": "von {n}",
    "talker.reconnect": "Noch einmal versuchen",
    "talker.send": "Eine Sammlung senden ...",
    "talker.sending": "Eine Sammlung senden",
    "talker.title": "Dein Talker",
    "talker.used": "{used} von {total} KiB belegt",
  },
  "en": {
    "cable.failed": "Sending failed: {error}",
    "cable.failed_reading": "Reading the device failed: {error}",
    "cable.failed_short": "failed",
    "cable.looking": "Looking for the device ...",
    "cable.firmware": "The device reports firmware {version}.",
    "cable.firmware_unnamed": "The device does not name its firmware, so it carries a build from before this line existed. Sending works all the same.",
    "door.browsers": "Chrome and Edge can talk to the cable. In Firefox and Safari the second line is the whole page - checking a file and seeing the boards still works.",
    "door.connect": "Connect the talker",
    "door.failed": "Nothing answered. Is the device awake? Only a key press brings it out of sleep, not the cable.",
    "door.wake_lead": "A key press brings the talker out of sleep. The cable does not - so press one before connecting.",
    "door.wake_title": "Wake it, then plug it in",
    "door.without": "No talker to hand? Check a file anyway",
    "err.cable_no_device": "Nothing answered. Is the cable in, and is the device awake? Only a key press brings it out of sleep, not the cable. The next press will ask for the port again.",
    "err.cable_device_older": "The device answered, but it speaks an older version of the cable (version {device}, this page speaks {browser}). It is not broken - it needs newer firmware. Nothing on the device has changed; it still reads the state it had.",
    "err.cable_device_newer": "The device answered, but it speaks a newer version of the cable (version {device}, this page speaks {browser}). That makes this page the older half: reload it and try again. Nothing on the device has changed.",
    "cable.no_serial": "Chrome and Edge can talk to the cable, this browser cannot - so there is nothing to press here.",
    "cable.cost": "This collection needs {total} KiB. {already} KiB of that is already on the device, so {needed} KiB go across; {free} KiB free afterwards.",
    "cable.cost_collections": "The device holds {on} of {room} collections afterwards.",
    "cable.cost_one": "This device holds exactly one collection. What is on it now is replaced - older firmware cannot hold several side by side.",
    "cable.nothing": "The device already has this state.",
    "cable.plan": "{put} {put|file|files} to send ({size} KiB), {remove} to remove, {keep} already there.",
    "cable.removing": "removing {done}/{total}: {name}",
    "cable.same_name": "There is already another collection on the device called “{name}”. The menu will then have two entries with the same name - nothing breaks and both stay on the device, but there is no telling which is which. To avoid that, give the collection or its first page a different name in the editor and export again.",
    "cable.sending": "sending {done}/{total}: {name}",
    "cable.sent": "Sent: {stored} {stored|file|files} stored, {removed} removed, {size} KiB through the cable.",
    "cable.sent_short": "sent",
    "cable.smaller": "The recordings go across compressed - the device says it plays them.",
    "cable.smaller_unheard": "This talker does not play compressed recordings, so they go across as they always did. It carries a build from before that existed - a newer firmware is what changes it.",
    "cable.stopped": "Stopped. Nothing on the device has changed - it still reads the state it had.",
    "cable.stopped_short": "stopped",
    "cable.stopped_tight": "Stopped after room had already been made: until a transfer runs through once, the device has silent keys.",
    "cable.tight": "There is no room for the old content and the new at once - so the clearing goes first. Stopping now leaves the device incomplete.",
    "cable.timings": "Longest gap {gap} ms, longest write {stall} ms. The device gives up after 4000 ms.",
    "err.cable_too_many": "The device has room for {room} collections and would then hold {on}. Remove one first - further down this page.",
    "err.cable_unreadable_collection": "There is a collection on the device this page cannot read ({name}). While it is there, nothing can say which tiles are still needed - so nothing is removed.",
    "err.cable_too_big": "This state does not fit on the device: {size} KiB built, {free} KiB free. Fewer pages, or shorter sentences.",
    "err.device_bad": "The device understood the word and not the rest of the line. That is a line that arrived damaged rather than anything wrong with the file; nothing was stored. Try again.",
    "err.device_crc": "A file arrived whole and does not match its checksum - something changed it on the way. It was thrown away rather than stored. Try again; if it happens twice at the same file, the cable is the suspect.",
    "err.device_lost": "The device's file system stopped taking bytes halfway through a file, which usually means it is full. The half-written file was thrown away. Remove a collection further down this page and send again.",
    "err.device_missing": "The device has no file called {name} - it was there when the list was read. Ask again; what the device holds has changed since.",
    "err.device_nospace": "A file is bigger than the room left on the device. It was refused before any of it was sent. Remove a collection further down, or send the recordings smaller.",
    "err.device_session": "The device had already closed the conversation when this arrived. It does that when a transfer breaks off, and then refuses everything until it is greeted again. Pressing again starts a new one. Nothing was left half-written.",
    "err.device_short": "The device waited for the rest of a file and it never came. The half-written file was thrown away, so there is no half a file on the device. Try again - and if it happens at the same place every time, it is the cable or the port rather than the file.",
    "err.device_verb": "The device does not know one of the words this page used, so its firmware is older than this page. The version check usually catches that first; if you are reading this, the two are further apart than either of them knows.",
    "err.device_write": "The device could not write the file ({name}), and why is not knowable from here - a file system that has become unreadable is the usual reason. Nothing was stored under that name.",
    "flash.carries": "This page carries firmware {release}.",
    "flash.check": "Check the device",
    "flash.update_to": "Update to {release}",
    "flash.write_to": "Write {release}",
    "flash.writes_device": "writes the device",
    "flash.check_lead": "The device has to be awake - only a key press brings it out of sleep, not the cable.",
    "flash.checking": "Asking the device ...",
    "flash.device_says": "The device carries firmware {version}.",
    "flash.device_unnamed": "The device answers but does not name its firmware: a build from before that line existed.",
    "flash.same": "That is exactly what this page carries. There is nothing to do.",
    "flash.older": "This page carries {release} and can write the program again.",
    "flash.newer": "The device is newer than what this page carries. That makes the page the older half, and there is nothing to write here.",
    "flash.unorderable": "{device} and {release} cannot be compared - a build somebody compiled themselves carries no number. Writing still works; the decision is yours.",
    "flash.nothing_answered": "Nothing answered. Either the device is asleep - a key press wakes it - or there is no talker on this port, or it has no firmware yet.",
    "flash.whole_warning": "This writes the bootloader, the partition table and the program. Any content on the device is gone afterwards: it starts empty and is filled again through the cable.",
    "flash.program_warning": "This writes the program only. The content on the device stays where it is - and so does the partition table. A device still carrying the old one keeps its smaller file area until everything is written once.",
    "flash.unnamed_unorderable": "There is nothing to compare with {release}: this build does not name itself. Writing still works; the decision is yours.",
    "flash.write_mode_here": "This page will put the device into write mode itself - on a finished talker BOOT and RESET are inside the case and out of reach. The port disappears and comes back as a different one while it happens, and the browser then asks again: USB JTAG/serial debug unit is the one to choose.",
    "flash.switching": "Switching ...",
    "flash.download_mode": "Nothing answered, so this page cannot switch it over either: that has to happen on the board - hold BOOT, tap RESET, release BOOT. On a finished talker both are inside the case, and then the only ways are to open it or to switch the board over before it is closed.",
    "flash.choose_and_write": "Choose the port and write",
    "flash.fetching": "Fetching the firmware ...",
    "flash.fetched": "Firmware fetched and checked: {size} KiB.",
    "flash.writing": "writing {done} of {total} KiB",
    "flash.written": "Written. The device restarts; if it stays dark, press RESET once. Check the device then says what is on it now.",
    "flash.written_short": "written",
    "flash.failed": "Writing failed: {error}",
    "flash.failed_short": "failed",
    "err.flash_no_chip": "No chip in write mode answered on this port. Write mode is a different port from the running talker's: hold BOOT, tap RESET, release BOOT - and then choose the port that has just appeared.",
    "err.flash_write_failed": "Writing stopped halfway. The device may be carrying part of a program now; it can be repeated, and nothing worse happens in between.",
    "err.firmware_not_fetched": "This page could not load its firmware file. Reload and try again.",
    "err.firmware_wrong_size": "The firmware file that arrived is not the length this page expects - it was cut short on the way. Nothing was written.",
    "err.firmware_wrong_sum": "The firmware file that arrived does not match its checksum. Nothing was written.",
    "err.firmware_no_digest": "This browser cannot compute a checksum here, which only happens on pages that are not served over https. Nothing is written unchecked.",
    "load.again": "Choose another file",
    "load.bad_sleep": "The sleep timeout in this file is not a number of seconds the device can read: {value}.",
    "load.collections_check": "Have a look",
    "load.collections_keep": "Keep it",
    "load.collections_lead": "What is on the device, collection by collection - and the way to get rid of one. The device has to be awake.",
    "load.collections_none": "There is no collection on the device. The device says the same thing itself, in the menu under Content.",
    "load.collections_older": "This firmware holds exactly one collection, under a fixed name - what it is called is not in the file. Newer firmware holds several side by side; what this page carries is further down.",
    "load.collections_really": "Remove it",
    "load.collections_remove": "Remove",
    "load.collections_removed": "“{name}” is gone: {files} {files|file|files} removed, {size} KiB freed.",
    "load.collections_removed_short": "removed",
    "load.collections_room": "{on} of {room} {room|collection|collections} on the device, {free} KiB free.",
    "load.collections_title": "The collections on the device",
    "load.collections_unreadable": "This page does not read {file} - a collection from another version of the format. It stays where it is: which tiles it needs cannot be said from here.",
    "load.collections_warning": "“{name}” goes off the device, along with every tile and recording no other collection still needs: {frees} KiB. This cannot be undone - the collection comes back from the editor if it is still there.",
    "load.cost": "What does it cost?",
    "load.compile_failed": "Compiling failed: {error}",
    "load.compiled": "{files} {files|file|files}, {size} KiB for the device.",
    "load.compiling": "Rendering the pictures and the table ...",
    "load.connect": "Choose the port ...",
    "load.connect_lead": "Plug the cable in and press a key on the device so that it is awake - only a key press brings it out of sleep, not the cable. Then choose the port here; the browser will ask.",
    "load.firmware_title": "The firmware on the device",
    "load.folder": "write them into a folder",
    "load.folder_failed": "Writing into the folder failed: {error}",
    "load.folder_lead": "The same files onto the disk, for mklittlefs or the bench - {action}.",
    "load.folder_written": "{written} {written|file|files} written into {folder}, {removed} removed, {size} KiB.",
    "load.here": "The file stays on this computer. It is read here and compiled here, and the only thing that leaves is what runs down the cable into the talker.",
    "load.holds": "{sets} {sets|page|pages}, {filled} of {keys} keys with something on them, {pictures} {pictures|picture|pictures}, {sounds} {sounds|recording|recordings}.",
    "load.holds_collection": "The device menu calls this collection “{name}”.",
    "load.holds_language": "The device labels itself in {name}.",
    "load.holds_no_voice": "No voice in this file - every key stays silent.",
    "load.holds_voice": "Spoken by {voice}.",
    "lang.de": "German",
    "lang.en": "English",
    "load.lead": "This page takes a file the editor wrote for the device, checks it, turns it into what the talker reads, and sends it down the cable.",
    "load.long_clip": "{label} key {slot}: “{text}” runs for {seconds} s. For that whole time the key answers no press - the device finishes a word before it listens again.",
    "load.name_cut": "{label}: the name is {bytes} bytes long and the device cuts it after {max}.",
    "load.no_picture": "{label} key {slot}: there is no picture for {symbol} in this file - the key shows a grey cross.",
    "load.not_a_package": "{name} is not a file for the talker: {why}.",
    "load.nothing_wrong": "Nothing here stands in the way.",
    "load.chip_blocked": "not here",
    "load.chip_notes": "{n} {n|note|notes}",
    "load.chip_refuses": "{n} {n|refusal|refusals}",
    "load.chip_size": "{size} KiB",
    "load.drop": "Drop the .obz here",
    "load.gate": "This browser cannot reach the device. The cable needs Chrome or Edge. You can still check a file here and see what the device would show.",
    "load.gate_more": "Open this page in Chrome or Edge when you have the talker in front of you.",
    "load.notes_stand": "The notes from the check still stand - nothing here made them worse.",
    "load.pick": "Choose a file ...",
    "load.pick_hint": "The .obz the editor writes under “Export this collection”, answering “For the talker” - in the ⋯ beside the collection's name.",
    "load.port": "Port USB {vendor}:{product}",
    "load.port_plain": "A port the browser does not name",
    "load.ports": "{n} ports granted - which of them is the talker shows when it is sent.",
    "load.preview": "What the device will show",
    "load.preview_empty": "nothing on it",
    "load.preview_key": "Key {n}: {what}",
    "load.preview_lead": "Every tile is the size a key on the device really is: 15.21 mm. And these are the pictures that are about to go down the cable, not a prediction of them.",
    "load.preview_setkey": "Page key",
    "load.reading": "Reading {name} ...",
    "load.refused": "This file cannot go onto the device as it is.",
    "load.send": "Send",
    "load.send_lead": "Everything the device does not have yet goes across; what it already has stays where it is.",
    "load.set": "Page {n}",
    "load.set_named": "Page {n} ({name})",
    "load.sleep_clamped": "The sleep timeout says {value} seconds, and the device takes only {min} to {max}. It will fall asleep after {used}.",
    "load.silent_key": "{label} key {slot}: there is no recording for “{text}” in this file - the key stays silent.",
    "load.silent_key_untexted": "{label} key {slot}: this key has no words and no recording - it stays silent.",
    "load.smaller": "Send the recordings smaller",
    "load.smaller_lead": "A quarter of the size and a quarter of the wait at the cable, at audibly lower quality. Right for a game, where the recordings are words to be matched; wrong for a collection somebody is understood through.",
    "load.step_check": "Check",
    "load.step_check_ahead": "What is in the file, and what of it the talker cannot do. Nothing is changed.",
    "load.step_compile": "Compile",
    "load.step_compile_ahead": "The pictures, the recordings and the pages, turned into the few files the talker reads.",
    "load.step_connect": "Connect",
    "load.step_connect_ahead": "Which talker this goes to. Asked once; after that the browser remembers the port.",
    "load.step_file": "Choose the file",
    "load.step_send": "Send",
    "load.step_send_ahead": "File by file down the cable, with how far it has got beside it. Nothing on the device has changed until here.",
    "load.stop": "Stop",
    "load.title": "Onto the talker",
    "load.too_many_keys": "{label}: {keys} keys, and the device has {max} to a page. The ones past that never arrive.",
    "load.too_many_sets": "{sets} pages, and the device has room for {max}. It would refuse this file and then show nothing at all. Remove pages in the editor and write it out again.",
    "load.unknown_language": "The device does not know the language {code} - its own prompts would stay English.",
    "load.wont_decode": "The picture for {symbol} cannot be read here - the key shows a grey cross.",
    "talker.back": "Your talker",
    "talker.fact_collections": "Collections",
    "talker.fact_firmware": "Firmware",
    "talker.fact_room": "Room left",
    "talker.holding": "What it is holding",
    "talker.of": "of {n}",
    "talker.reconnect": "Try again",
    "talker.send": "Send a collection ...",
    "talker.sending": "Send a collection",
    "talker.title": "Your talker",
    "talker.used": "{used} of {total} KiB used",
  },
};
