#!/usr/bin/env python3
"""Writes static/boot_data.js: what app.py injects, for the page that has none.

    python3 tools/bootdata.py            # rewrite the file
    python3 tools/bootdata.py --check    # say whether it is stale, write nothing

ui.html carries a `<script type="application/json" id="bootstrap">` that app.py
fills in as it serves the page - the language, its text table, the palette and
the set limits. A static site has nobody to fill it in, and those values still
have to come from somewhere.

Generated rather than written by hand, and generated rather than fetched.

*Generated*, because texts.py is the source and has to stay the source. It is
not only the page's table: the build log, the OBF converter and every command
line message come out of the same dict, in two languages that tests/german.py
and tests/test_ui_texts.py already hold level with each other. A second copy
maintained by hand would drift, and the drift would be invisible until
somebody read the page in the language they do not speak.

*Not fetched*, because t() is synchronous and called from everywhere. A JSON
file would make the table arrive after the first render, and every label on the
page would have to learn to appear late. A module is imported before anything
runs, which is what the current arrangement gives and what this has to match.

Only the ui.* entries, the same subset ui_texts() hands over today. The build
log's keys have no business on the page, and there are 84 of them per language.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import layout  # noqa: E402
import texts  # noqa: E402

TARGET = ROOT / "static" / "boot_data.js"

HEADER = '''// Generated by tools/bootdata.py - do not edit.
//
// What app.py puts into ui.html's bootstrap block, written out for a page that
// is served by nobody. texts.py is the source; tests/test_boot_data.py fails
// if this file has drifted from it, so the way to change a label is still to
// change texts.py and run the generator.
//
// Only the ui.* entries, in every language the product has. The server picks
// one and sends that; here both travel, because there is no server to do the
// picking and the choice is the reader's.
'''


def payload() -> dict:
    return {
        "languages": sorted(texts.TEXTS),
        "default": texts.DEFAULT,
        "texts": {
            lang: {key: value for key, value in table.items()
                   if key.startswith("ui.")}
            for lang, table in sorted(texts.TEXTS.items())
        },
        "palette": layout.DEFAULT_PALETTE,
        "limits": {
            "maxSets": layout.MAX_SETS,
            "maxActive": layout.MAX_ACTIVE_SETS,
        },
    }


def render() -> str:
    data = payload()
    parts = [HEADER]
    parts.append("\nexport const LANGUAGES = "
                 f"{json.dumps(data['languages'])};\n")
    parts.append("export const DEFAULT_LANGUAGE = "
                 f"{json.dumps(data['default'])};\n")
    parts.append("export const PALETTE = "
                 f"{json.dumps(data['palette'])};\n")
    parts.append("export const LIMITS = "
                 f"{json.dumps(data['limits'])};\n")
    # One object per language, sorted, one key per line: this file is read in
    # diffs far more often than it is read whole, and a changed label should be
    # one changed line rather than a rewritten blob.
    parts.append("\nexport const TEXTS = {\n")
    for lang in data["languages"]:
        parts.append(f"  {json.dumps(lang)}: {{\n")
        for key, value in sorted(data["texts"][lang].items()):
            parts.append(f"    {json.dumps(key)}: "
                         f"{json.dumps(value, ensure_ascii=False)},\n")
        parts.append("  },\n")
    parts.append("};\n")
    return "".join(parts)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the file is stale, and write nothing")
    args = parser.parse_args(argv)

    wanted = render()
    if args.check:
        if not TARGET.exists():
            print(f"{TARGET.relative_to(ROOT)} is missing - run "
                  f"python3 tools/bootdata.py")
            return 1
        if TARGET.read_text(encoding="utf-8") != wanted:
            print(f"{TARGET.relative_to(ROOT)} is stale - run "
                  f"python3 tools/bootdata.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} matches texts.py")
        return 0

    TARGET.write_text(wanted, encoding="utf-8")
    counts = ", ".join(f"{lang} {len(t)}" for lang, t in
                       sorted(payload()["texts"].items()))
    print(f"wrote {TARGET.relative_to(ROOT)} ({counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
